// No include guard, we need to include this file multiple times
#include "WrapperMemory.h"

// Undefine Unicode (and some other) wrapper macros
#undef min
#undef max
#undef GetObject
#undef SetCurrentDirectory
#undef CreateFile
#undef CopyFile
#undef MoveFile
#undef DeleteFile
#undef GetBinaryType
#undef MessageBox
#undef GetFreeSpace
#undef PlaySound
#undef RegisterClass
#undef CreateEvent
#undef GetFirstChild
#undef GetNextSibling
#undef GetPrevSibling
#undef GetWindowStyle
#undef GetShortPathName
#undef GetLongPathName
#undef GetFullPathName
#undef GetFileAttributes
#undef EnumResourceTypes
#undef LoadImage
#undef UpdateResource
#undef BeginUpdateResource
#undef EndUpdateResource
#undef EnumResourceLanguages
#undef FormatMessage
#undef GetCommandLine
#undef CreateProcess
#undef GetUserName
#undef GetClassName
#undef FindFirstFile
#undef FindNextFile
#undef GetEnvironmentVariable
#undef SetEnvironmentVariable
#undef ExitWindows
#undef GetCompressedFileSize
#undef GetTempPath
#undef CreateDirectory
#undef CompareString
#undef EnumDisplayDevices
#undef ExpandEnvironmentStrings
#undef EnumResourceNames
#undef GetMessage
#undef OpenService
#undef CreateService
#undef WriteConsole
#undef CreateProcess
#undef CreateDirectory
#undef RemoveDirectory
#undef GetCurrentDirectory
#undef SetCurrentDirectory
#undef SetPort
#undef CreateFont
#undef SendMessage
#undef SendMessageTimeout
#undef SendMessageCallback
#undef SendNotifyMessage
#undef PostMessage
#undef PostThreadMessage
#undef InsertMenu
#undef Yield
